/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 58GpZjZCWTaJ8AUhpCwt2K

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 58GpZjZCWTaJ8AUhpCwt2K/projectModule

const data = {
  base: `${"plasmic_tokens_58GpZjZCWTaJ8AUhpCwt2K"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
