/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: hjKYmYi6HMwK6TRyk7ew5R

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: hjKYmYi6HMwK6TRyk7ew5R/projectModule

const data = {
  base: `${"plasmic_tokens_hjKYmYi6HMwK6TRyk7ew5R"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
