/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 67C2x4VH9CGyuASG98L3XF
// Component: p7cDk5onbOfu

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { ScrollMarquee } from "@/components/plasmic-components/ScrollMarquee"; // plasmic-import: K8ICcSEKq3PA/codeComponent
import { PaperTexture } from "@/components/plasmic-components/PaperTexture"; // plasmic-import: 9rVOQ6ot_kuJ/codeComponent
import { NextImage } from "@/components/plasmic-components/NextImage"; // plasmic-import: 6-H-ZX-IJsr_/codeComponent
import { NoiseOverlay } from "@/components/plasmic-components/NoiseOverlay"; // plasmic-import: GohQkMFtGYyn/codeComponent
import { _useGlobalVariants } from "../toothmonster/plasmic"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/projectModule
import { _useStyleTokens } from "../toothmonster/PlasmicStyleTokensProvider"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicMarqueeScroll.module.css"; // plasmic-import: p7cDk5onbOfu/css

createPlasmicElementProxy;

export type PlasmicMarqueeScroll__VariantMembers = {};
export type PlasmicMarqueeScroll__VariantsArgs = {};
type VariantPropType = keyof PlasmicMarqueeScroll__VariantsArgs;
export const PlasmicMarqueeScroll__VariantProps = new Array<VariantPropType>();

export type PlasmicMarqueeScroll__ArgsType = {};
type ArgPropType = keyof PlasmicMarqueeScroll__ArgsType;
export const PlasmicMarqueeScroll__ArgProps = new Array<ArgPropType>();

export type PlasmicMarqueeScroll__OverridesType = {
  root?: Flex__<typeof ScrollMarquee>;
  paperTexture?: Flex__<typeof PaperTexture>;
};

export interface DefaultMarqueeScrollProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMarqueeScroll__RenderFunc(props: {
  variants: PlasmicMarqueeScroll__VariantsArgs;
  args: PlasmicMarqueeScroll__ArgsType;
  overrides: PlasmicMarqueeScroll__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <ScrollMarquee
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        "root_reset_67C2x4VH9CGyuASG98L3XF",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        sty.root
      )}
      direction={"right"}
      height={"90px"}
      pauseOnHover={false}
    >
      <PaperTexture
        data-plasmic-name={"paperTexture"}
        data-plasmic-override={overrides.paperTexture}
        animate={false}
        className={classNames("__wab_instance", sty.paperTexture)}
        coverage={75}
        lumaBias={2}
        step={2}
      >
        <div className={classNames("all", sty.freeBox__rmTt9)}>
          <NextImage
            alt={""}
            className={classNames("__wab_instance", sty.image__egV8)}
            src={"/plasmic/toothmonster/images/marqueeSvg.svg"}
          />

          <NextImage
            alt={""}
            className={classNames("__wab_instance", sty.image__sFo8Y)}
            src={"/plasmic/toothmonster/images/marqueeSvg.svg"}
          />

          <div className={classNames("all", sty.freeBox__pEH1)}>
            <NoiseOverlay
              blendMode={"normal"}
              className={classNames("__wab_instance", sty.noiseOverlay___8IJlm)}
              color={true ? "#EADBC2" : undefined}
              grainSize={1}
              isolateBlend={false}
            />

            <NoiseOverlay
              blendMode={"multiply"}
              className={classNames("__wab_instance", sty.noiseOverlay__kpjVn)}
              color={true ? "#000000" : undefined}
              grainSize={1}
              isolateBlend={false}
              seed={3}
            />
          </div>
        </div>
      </PaperTexture>
    </ScrollMarquee>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "paperTexture"],
  paperTexture: ["paperTexture"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof ScrollMarquee;
  paperTexture: typeof PaperTexture;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMarqueeScroll__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMarqueeScroll__VariantsArgs;
    args?: PlasmicMarqueeScroll__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicMarqueeScroll__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicMarqueeScroll__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMarqueeScroll__ArgProps,
          internalVariantPropNames: PlasmicMarqueeScroll__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMarqueeScroll__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMarqueeScroll";
  } else {
    func.displayName = `PlasmicMarqueeScroll.${nodeName}`;
  }
  return func;
}

export const PlasmicMarqueeScroll = Object.assign(
  // Top-level PlasmicMarqueeScroll renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    paperTexture: makeNodeComponent("paperTexture"),

    // Metadata about props expected for PlasmicMarqueeScroll
    internalVariantProps: PlasmicMarqueeScroll__VariantProps,
    internalArgProps: PlasmicMarqueeScroll__ArgProps
  }
);

export default PlasmicMarqueeScroll;
/* prettier-ignore-end */
