/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 67C2x4VH9CGyuASG98L3XF
// Component: O81Fd1q4ueaL

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import NavBanner from "../../NavBanner"; // plasmic-import: uEuM32AhsVsN/component
import { InkBleed } from "@/components/plasmic-components/InkBleed"; // plasmic-import: x-cwBn9SIvTe/codeComponent
import { ContactForm } from "@/components/plasmic-components/ContactForm"; // plasmic-import: JivwNWK20kIt/codeComponent
import { ContactField } from "@/components/plasmic-components/ContactForm"; // plasmic-import: 5qwWzawLe4Hl/codeComponent
import Label from "../../Label"; // plasmic-import: BYBqjVrGPH5t/component
import TextInput from "../../TextInput"; // plasmic-import: ct_DnrV178NJ/component
import TextAreaInput from "../../TextAreaInput"; // plasmic-import: M9d78DwckmWy/component
import { ContactSubmit } from "@/components/plasmic-components/ContactForm"; // plasmic-import: xraZo1vHJbhP/codeComponent
import Footer from "../../Footer"; // plasmic-import: jjWjxw2fIQP_/component
import { _useGlobalVariants } from "../toothmonster/plasmic"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/projectModule
import { _useStyleTokens } from "../toothmonster/PlasmicStyleTokensProvider"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicContact.module.css"; // plasmic-import: O81Fd1q4ueaL/css

import RegistrationMarkTargetSvg2Icon from "../toothmonster/icons/PlasmicIcon__RegistrationMarkTargetSvg2"; // plasmic-import: eGWLBGxB6lSY/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicContact__VariantMembers = {};
export type PlasmicContact__VariantsArgs = {};
type VariantPropType = keyof PlasmicContact__VariantsArgs;
export const PlasmicContact__VariantProps = new Array<VariantPropType>();

export type PlasmicContact__ArgsType = {};
type ArgPropType = keyof PlasmicContact__ArgsType;
export const PlasmicContact__ArgProps = new Array<ArgPropType>();

export type PlasmicContact__OverridesType = {
  root?: Flex__<"div">;
  navBanner?: Flex__<typeof NavBanner>;
  section?: Flex__<"section">;
  h1?: Flex__<"h1">;
  contactForm?: Flex__<typeof ContactForm>;
  text?: Flex__<"div">;
  nameInput?: Flex__<typeof TextInput>;
  emailInput?: Flex__<typeof TextInput>;
  subjectInput?: Flex__<typeof TextInput>;
  textAreaInput?: Flex__<typeof TextAreaInput>;
  contactSubmitButton?: Flex__<typeof ContactSubmit>;
  svg?: Flex__<"svg">;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultContactProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicContact__RenderFunc(props: {
  variants: PlasmicContact__VariantsArgs;
  args: PlasmicContact__ArgsType;
  overrides: PlasmicContact__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "nameInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "emailInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "subjectInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "textAreaInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_67C2x4VH9CGyuASG98L3XF",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.root
          )}
        >
          <NavBanner
            data-plasmic-name={"navBanner"}
            data-plasmic-override={overrides.navBanner}
            bottomTear={true}
            className={classNames("__wab_instance", sty.navBanner)}
            color={"coral"}
          />

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames("all", sty.section)}
          >
            <InkBleed
              bleedColor={true ? "#00427F40" : undefined}
              className={classNames("__wab_instance", sty.inkBleed__aurVu)}
              noiseFrequency={1}
              spread={3}
            >
              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  "all",
                  "h1",
                  "h1__67C2x",
                  "__wab_text",
                  sty.h1
                )}
              >
                {"contact me"}
              </h1>
            </InkBleed>
            <InkBleed
              bleedColor={true ? "#00427F40" : undefined}
              className={classNames("__wab_instance", sty.inkBleed__nktew)}
              noiseFrequency={1}
              spread={4}
            >
              <div className={classNames("all", sty.freeBox__okMvB)}>
                <ContactForm
                  data-plasmic-name={"contactForm"}
                  data-plasmic-override={overrides.contactForm}
                  className={classNames("__wab_instance", sty.contactForm)}
                  errorContent={
                    <DataCtxReader__>
                      {$ctx => (
                        <React.Fragment>
                          {(() => {
                            try {
                              return $ctx.contactForm.errorMessage;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "Error";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      )}
                    </DataCtxReader__>
                  }
                >
                  <DataCtxReader__>
                    {$ctx => (
                      <React.Fragment>
                        <ContactField
                          className={classNames(
                            "__wab_instance",
                            sty.contactField__dUhcG
                          )}
                          errorContent={
                            <div
                              data-plasmic-name={"text"}
                              data-plasmic-override={overrides.text}
                              className={classNames(
                                "all",
                                "__wab_text",
                                sty.text
                              )}
                            >
                              {"Name is required."}
                            </div>
                          }
                          field={"name"}
                          required={true}
                        >
                          <Label
                            className={classNames(
                              "__wab_instance",
                              sty.label__n8K5K
                            )}
                            requirementIndicator={"required"}
                          >
                            {"Name"}
                          </Label>
                          <TextInput
                            data-plasmic-name={"nameInput"}
                            data-plasmic-override={overrides.nameInput}
                            className={classNames(
                              "__wab_instance",
                              sty.nameInput
                            )}
                            inputMode={"text"}
                            onChange={async (...eventArgs: any) => {
                              generateStateOnChangeProp($state, [
                                "nameInput",
                                "value"
                              ]).apply(null, eventArgs);

                              if (
                                eventArgs.length > 1 &&
                                eventArgs[1] &&
                                eventArgs[1]._plasmic_state_init_
                              ) {
                                return;
                              }
                            }}
                            placeholder={"Enter name"}
                            value={generateStateValueProp($state, [
                              "nameInput",
                              "value"
                            ])}
                          />
                        </ContactField>
                        <ContactField
                          className={classNames(
                            "__wab_instance",
                            sty.contactField___0MFsy
                          )}
                          errorContent={"Email is required."}
                          field={"email"}
                          required={true}
                        >
                          <Label
                            className={classNames(
                              "__wab_instance",
                              sty.label__uoKwh
                            )}
                            requirementIndicator={"required"}
                          >
                            {"Email"}
                          </Label>
                          <TextInput
                            data-plasmic-name={"emailInput"}
                            data-plasmic-override={overrides.emailInput}
                            className={classNames(
                              "__wab_instance",
                              sty.emailInput
                            )}
                            inputMode={"email"}
                            inputType={"email"}
                            onChange={async (...eventArgs: any) => {
                              generateStateOnChangeProp($state, [
                                "emailInput",
                                "value"
                              ]).apply(null, eventArgs);

                              if (
                                eventArgs.length > 1 &&
                                eventArgs[1] &&
                                eventArgs[1]._plasmic_state_init_
                              ) {
                                return;
                              }
                            }}
                            placeholder={"Enter email"}
                            value={generateStateValueProp($state, [
                              "emailInput",
                              "value"
                            ])}
                          />
                        </ContactField>
                        <ContactField
                          className={classNames(
                            "__wab_instance",
                            sty.contactField__yRq3M
                          )}
                          errorContent={"Subject line is required."}
                          field={"email"}
                          required={true}
                        >
                          <Label
                            className={classNames(
                              "__wab_instance",
                              sty.label___7JV9G
                            )}
                            requirementIndicator={"required"}
                          >
                            {"Subject"}
                          </Label>
                          <TextInput
                            data-plasmic-name={"subjectInput"}
                            data-plasmic-override={overrides.subjectInput}
                            className={classNames(
                              "__wab_instance",
                              sty.subjectInput
                            )}
                            inputMode={"text"}
                            onChange={async (...eventArgs: any) => {
                              generateStateOnChangeProp($state, [
                                "subjectInput",
                                "value"
                              ]).apply(null, eventArgs);

                              if (
                                eventArgs.length > 1 &&
                                eventArgs[1] &&
                                eventArgs[1]._plasmic_state_init_
                              ) {
                                return;
                              }
                            }}
                            placeholder={"Enter subject line"}
                            value={generateStateValueProp($state, [
                              "subjectInput",
                              "value"
                            ])}
                          />
                        </ContactField>
                        <ContactField
                          className={classNames(
                            "__wab_instance",
                            sty.contactField___3SoFk
                          )}
                          errorContent={"You need a message!"}
                          field={"email"}
                          required={true}
                        >
                          <Label
                            className={classNames(
                              "__wab_instance",
                              sty.label___7CnnT
                            )}
                            requirementIndicator={"required"}
                          >
                            {"Message"}
                          </Label>
                          <TextAreaInput
                            data-plasmic-name={"textAreaInput"}
                            data-plasmic-override={overrides.textAreaInput}
                            className={classNames(
                              "__wab_instance",
                              sty.textAreaInput
                            )}
                            inputMode={"text"}
                            onChange={async (...eventArgs: any) => {
                              generateStateOnChangeProp($state, [
                                "textAreaInput",
                                "value"
                              ]).apply(null, eventArgs);

                              if (
                                eventArgs.length > 1 &&
                                eventArgs[1] &&
                                eventArgs[1]._plasmic_state_init_
                              ) {
                                return;
                              }
                            }}
                            padded={[]}
                            value={generateStateValueProp($state, [
                              "textAreaInput",
                              "value"
                            ])}
                          />
                        </ContactField>
                        <div className={classNames("all", sty.freeBox__obP6Z)}>
                          <ContactSubmit
                            data-plasmic-name={"contactSubmitButton"}
                            data-plasmic-override={
                              overrides.contactSubmitButton
                            }
                            children={null}
                            className={classNames(
                              "__wab_instance",
                              sty.contactSubmitButton
                            )}
                            label={"Submit"}
                          />
                        </div>
                      </React.Fragment>
                    )}
                  </DataCtxReader__>
                </ContactForm>
                <RegistrationMarkTargetSvg2Icon
                  data-plasmic-name={"svg"}
                  data-plasmic-override={overrides.svg}
                  className={classNames("all", sty.svg)}
                  role={"img"}
                />
              </div>
            </InkBleed>
          </section>
          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBanner",
    "section",
    "h1",
    "contactForm",
    "text",
    "nameInput",
    "emailInput",
    "subjectInput",
    "textAreaInput",
    "contactSubmitButton",
    "svg",
    "footer"
  ],
  navBanner: ["navBanner"],
  section: [
    "section",
    "h1",
    "contactForm",
    "text",
    "nameInput",
    "emailInput",
    "subjectInput",
    "textAreaInput",
    "contactSubmitButton",
    "svg"
  ],
  h1: ["h1"],
  contactForm: [
    "contactForm",
    "text",
    "nameInput",
    "emailInput",
    "subjectInput",
    "textAreaInput",
    "contactSubmitButton"
  ],
  text: ["text"],
  nameInput: ["nameInput"],
  emailInput: ["emailInput"],
  subjectInput: ["subjectInput"],
  textAreaInput: ["textAreaInput"],
  contactSubmitButton: ["contactSubmitButton"],
  svg: ["svg"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBanner: typeof NavBanner;
  section: "section";
  h1: "h1";
  contactForm: typeof ContactForm;
  text: "div";
  nameInput: typeof TextInput;
  emailInput: typeof TextInput;
  subjectInput: typeof TextInput;
  textAreaInput: typeof TextAreaInput;
  contactSubmitButton: typeof ContactSubmit;
  svg: "svg";
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicContact__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicContact__VariantsArgs;
    args?: PlasmicContact__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicContact__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicContact__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicContact__ArgProps,
          internalVariantPropNames: PlasmicContact__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicContact__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicContact";
  } else {
    func.displayName = `PlasmicContact.${nodeName}`;
  }
  return func;
}

export const PlasmicContact = Object.assign(
  // Top-level PlasmicContact renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBanner: makeNodeComponent("navBanner"),
    section: makeNodeComponent("section"),
    h1: makeNodeComponent("h1"),
    contactForm: makeNodeComponent("contactForm"),
    text: makeNodeComponent("text"),
    nameInput: makeNodeComponent("nameInput"),
    emailInput: makeNodeComponent("emailInput"),
    subjectInput: makeNodeComponent("subjectInput"),
    textAreaInput: makeNodeComponent("textAreaInput"),
    contactSubmitButton: makeNodeComponent("contactSubmitButton"),
    svg: makeNodeComponent("svg"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicContact
    internalVariantProps: PlasmicContact__VariantProps,
    internalArgProps: PlasmicContact__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/contact",
      pagePath: "/contact",
      params: {},
      query: {}
    })
  }
);

export default PlasmicContact;
/* prettier-ignore-end */
