/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 67C2x4VH9CGyuASG98L3XF
// Component: FuUP13USuDR8

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import NavBanner from "../../NavBanner"; // plasmic-import: uEuM32AhsVsN/component
import { RevealOnScroll } from "@/components/plasmic-components/RevealOnScroll"; // plasmic-import: kqOT32TkSKDq/codeComponent
import { NoiseOverlay } from "@/components/plasmic-components/NoiseOverlay"; // plasmic-import: GohQkMFtGYyn/codeComponent
import { GradientBlob } from "@/components/plasmic-components/GradientBlob"; // plasmic-import: e8qsCr99-93Q/codeComponent
import { TornSection } from "@/components/plasmic-components/TornSection"; // plasmic-import: 8y_E0U1V1ob-/codeComponent
import { ModelViewer } from "@/components/plasmic-components/ModelViewer"; // plasmic-import: F99Tz_Qd8rVB/codeComponent
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: FuUP13USuDR8/css

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  navBanner?: Flex__<typeof NavBanner>;
  revealOnScroll?: Flex__<typeof RevealOnScroll>;
  noiseOverlay?: Flex__<typeof NoiseOverlay>;
  gradientBlob?: Flex__<typeof GradientBlob>;
  tornSection?: Flex__<typeof TornSection>;
  columns?: Flex__<"div">;
  _3DModelViewer?: Flex__<typeof ModelViewer>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "opacity",
        type: "private",
        variableType: "number",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => 0
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <NavBanner
            data-plasmic-name={"navBanner"}
            data-plasmic-override={overrides.navBanner}
            bottomTear={true}
            className={classNames("__wab_instance", sty.navBanner)}
            color={"midnight"}
            effect={
              <RevealOnScroll
                data-plasmic-name={"revealOnScroll"}
                data-plasmic-override={overrides.revealOnScroll}
                className={classNames("__wab_instance", sty.revealOnScroll)}
                playOnce={false}
                scrollMode={"page"}
                triggerPoint={120}
              >
                <NoiseOverlay
                  data-plasmic-name={"noiseOverlay"}
                  data-plasmic-override={overrides.noiseOverlay}
                  animate={"always"}
                  className={classNames("__wab_instance", sty.noiseOverlay)}
                  color={true ? "#201B2A" : undefined}
                />

                <GradientBlob
                  data-plasmic-name={"gradientBlob"}
                  data-plasmic-override={overrides.gradientBlob}
                  className={classNames("__wab_instance", sty.gradientBlob)}
                  color1={true ? "#00427F" : undefined}
                  color2={true ? "#FF6A50" : undefined}
                  color3={true ? "#52A159" : undefined}
                  color4={true ? "#CEBEE3" : undefined}
                />
              </RevealOnScroll>
            }
            effectVisible={true}
            shadow={true}
          />

          <TornSection
            data-plasmic-name={"tornSection"}
            data-plasmic-override={overrides.tornSection}
            backgroundColor={"midnight"}
            className={classNames("__wab_instance", sty.tornSection)}
            tornBottom={true}
            tornBottomDepth={
              hasVariant(globalVariants, "screen", "mobile") ? 2 : undefined
            }
            tornBottomStepSize={
              hasVariant(globalVariants, "screen", "mobile") ? 6 : undefined
            }
          >
            <div
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column___2GzTv)}>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.h1__67C2x,
                    projectcss.__wab_text,
                    sty.h1__g57Iq
                  )}
                >
                  {"You won't believe what happens next."}
                </h1>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.h1__67C2x,
                    projectcss.__wab_text,
                    sty.h1___2PyZv
                  )}
                >
                  {"You won't believe what happens next."}
                </h1>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.h1__67C2x,
                    projectcss.__wab_text,
                    sty.h1___4Baho
                  )}
                >
                  {"You won't believe what happens next."}
                </h1>
              </div>
              <div className={classNames(projectcss.all, sty.column___77LZa)}>
                <ModelViewer
                  data-plasmic-name={"_3DModelViewer"}
                  data-plasmic-override={overrides._3DModelViewer}
                  className={classNames("__wab_instance", sty._3DModelViewer)}
                  enableZoom={false}
                  environment={"park"}
                  fallbackImageUrl={
                    "/plasmic/toothmonster/images/tooth3DiconGif.gif"
                  }
                  minDistance={5}
                  modelUrl={"/models/tooth.glb"}
                />
              </div>
            </div>
          </TornSection>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBanner",
    "revealOnScroll",
    "noiseOverlay",
    "gradientBlob",
    "tornSection",
    "columns",
    "_3DModelViewer"
  ],
  navBanner: ["navBanner", "revealOnScroll", "noiseOverlay", "gradientBlob"],
  revealOnScroll: ["revealOnScroll", "noiseOverlay", "gradientBlob"],
  noiseOverlay: ["noiseOverlay"],
  gradientBlob: ["gradientBlob"],
  tornSection: ["tornSection", "columns", "_3DModelViewer"],
  columns: ["columns", "_3DModelViewer"],
  _3DModelViewer: ["_3DModelViewer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBanner: typeof NavBanner;
  revealOnScroll: typeof RevealOnScroll;
  noiseOverlay: typeof NoiseOverlay;
  gradientBlob: typeof GradientBlob;
  tornSection: typeof TornSection;
  columns: "div";
  _3DModelViewer: typeof ModelViewer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBanner: makeNodeComponent("navBanner"),
    revealOnScroll: makeNodeComponent("revealOnScroll"),
    noiseOverlay: makeNodeComponent("noiseOverlay"),
    gradientBlob: makeNodeComponent("gradientBlob"),
    tornSection: makeNodeComponent("tornSection"),
    columns: makeNodeComponent("columns"),
    _3DModelViewer: makeNodeComponent("_3DModelViewer"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/",
      pagePath: "/",
      params: {},
      query: {}
    })
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
