/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 67C2x4VH9CGyuASG98L3XF
// Component: uEuM32AhsVsN

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/projectcss
import sty from "./PlasmicNavBanner.module.css"; // plasmic-import: uEuM32AhsVsN/css

createPlasmicElementProxy;

export type PlasmicNavBanner__VariantMembers = {
  color: "midnight" | "navy" | "coral" | "cream";
  effectVisible: "effectVisible";
  bottomTear: "bottomTear";
  blurredBg: "blurredBg";
  shadow: "shadow";
};
export type PlasmicNavBanner__VariantsArgs = {
  color?: SingleChoiceArg<"midnight" | "navy" | "coral" | "cream">;
  effectVisible?: SingleBooleanChoiceArg<"effectVisible">;
  bottomTear?: SingleBooleanChoiceArg<"bottomTear">;
  blurredBg?: SingleBooleanChoiceArg<"blurredBg">;
  shadow?: SingleBooleanChoiceArg<"shadow">;
};
type VariantPropType = keyof PlasmicNavBanner__VariantsArgs;
export const PlasmicNavBanner__VariantProps = new Array<VariantPropType>(
  "color",
  "effectVisible",
  "bottomTear",
  "blurredBg",
  "shadow"
);

export type PlasmicNavBanner__ArgsType = {};
type ArgPropType = keyof PlasmicNavBanner__ArgsType;
export const PlasmicNavBanner__ArgProps = new Array<ArgPropType>();

export type PlasmicNavBanner__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultNavBannerProps {
  color?: SingleChoiceArg<"midnight" | "navy" | "coral" | "cream">;
  effectVisible?: SingleBooleanChoiceArg<"effectVisible">;
  bottomTear?: SingleBooleanChoiceArg<"bottomTear">;
  blurredBg?: SingleBooleanChoiceArg<"blurredBg">;
  shadow?: SingleBooleanChoiceArg<"shadow">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNavBanner__RenderFunc(props: {
  variants: PlasmicNavBanner__VariantsArgs;
  args: PlasmicNavBanner__ArgsType;
  overrides: PlasmicNavBanner__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "color",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.color
      },
      {
        path: "effectVisible",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          $props.effectVisible
      },
      {
        path: "bottomTear",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.bottomTear
      },
      {
        path: "blurredBg",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.blurredBg
      },
      {
        path: "shadow",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.shadow
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        {
          [sty.rootblurredBg]: hasVariant($state, "blurredBg", "blurredBg"),
          [sty.rootbottomTear]: hasVariant($state, "bottomTear", "bottomTear"),
          [sty.rootcolor_coral]: hasVariant($state, "color", "coral"),
          [sty.rootcolor_cream]: hasVariant($state, "color", "cream"),
          [sty.rootcolor_midnight]: hasVariant($state, "color", "midnight"),
          [sty.rootcolor_navy]: hasVariant($state, "color", "navy"),
          [sty.rooteffectVisible]: hasVariant(
            $state,
            "effectVisible",
            "effectVisible"
          ),
          [sty.rootshadow]: hasVariant($state, "shadow", "shadow")
        }
      )}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavBanner__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavBanner__VariantsArgs;
    args?: PlasmicNavBanner__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicNavBanner__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicNavBanner__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNavBanner__ArgProps,
          internalVariantPropNames: PlasmicNavBanner__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavBanner__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavBanner";
  } else {
    func.displayName = `PlasmicNavBanner.${nodeName}`;
  }
  return func;
}

export const PlasmicNavBanner = Object.assign(
  // Top-level PlasmicNavBanner renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicNavBanner
    internalVariantProps: PlasmicNavBanner__VariantProps,
    internalArgProps: PlasmicNavBanner__ArgProps
  }
);

export default PlasmicNavBanner;
/* prettier-ignore-end */
