/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 67C2x4VH9CGyuASG98L3XF
// Component: uEuM32AhsVsN

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { TornSection } from "@/components/plasmic-components/TornSection"; // plasmic-import: 8y_E0U1V1ob-/codeComponent
import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/projectcss
import sty from "./PlasmicNavBanner.module.css"; // plasmic-import: uEuM32AhsVsN/css

createPlasmicElementProxy;

export type PlasmicNavBanner__VariantMembers = {
  color: "midnight" | "navy" | "coral" | "cream";
  effectVisible: "effectVisible";
  bottomTear: "bottomTear";
  blurredBg: "blurredBg";
  shadow: "shadow";
};
export type PlasmicNavBanner__VariantsArgs = {
  color?: SingleChoiceArg<"midnight" | "navy" | "coral" | "cream">;
  effectVisible?: SingleBooleanChoiceArg<"effectVisible">;
  bottomTear?: SingleBooleanChoiceArg<"bottomTear">;
  blurredBg?: SingleBooleanChoiceArg<"blurredBg">;
  shadow?: SingleBooleanChoiceArg<"shadow">;
};
type VariantPropType = keyof PlasmicNavBanner__VariantsArgs;
export const PlasmicNavBanner__VariantProps = new Array<VariantPropType>(
  "color",
  "effectVisible",
  "bottomTear",
  "blurredBg",
  "shadow"
);

export type PlasmicNavBanner__ArgsType = {};
type ArgPropType = keyof PlasmicNavBanner__ArgsType;
export const PlasmicNavBanner__ArgProps = new Array<ArgPropType>();

export type PlasmicNavBanner__OverridesType = {
  root?: Flex__<typeof TornSection>;
  navigationBar?: Flex__<typeof NavigationBar>;
  freeBox?: Flex__<"div">;
};

export interface DefaultNavBannerProps {
  color?: SingleChoiceArg<"midnight" | "navy" | "coral" | "cream">;
  effectVisible?: SingleBooleanChoiceArg<"effectVisible">;
  bottomTear?: SingleBooleanChoiceArg<"bottomTear">;
  blurredBg?: SingleBooleanChoiceArg<"blurredBg">;
  shadow?: SingleBooleanChoiceArg<"shadow">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNavBanner__RenderFunc(props: {
  variants: PlasmicNavBanner__VariantsArgs;
  args: PlasmicNavBanner__ArgsType;
  overrides: PlasmicNavBanner__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "color",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.color
      },
      {
        path: "effectVisible",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) =>
          $props.effectVisible
      },
      {
        path: "bottomTear",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.bottomTear
      },
      {
        path: "blurredBg",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.blurredBg
      },
      {
        path: "shadow",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.shadow
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <TornSection
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        "__wab_instance",
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <NavigationBar
        data-plasmic-name={"navigationBar"}
        data-plasmic-override={overrides.navigationBar}
        brand={
          <PlasmicLink__
            className={classNames(
              projectcss.all,
              projectcss.a,
              projectcss.a__67C2x,
              sty.link__xBeoZ
            )}
            component={Link}
            href={"#"}
            legacyBehavior={false}
            platform={"nextjs"}
          >
            <PlasmicImg__
              alt={""}
              className={classNames(sty.img__enFiB)}
              displayHeight={"40px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"none"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"auto"}
              src={"https://static1.plasmic.app/nav-logo-placeholder.svg"}
            />
          </PlasmicLink__>
        }
        className={classNames("__wab_instance", sty.navigationBar, {
          [sty.navigationBarbottomTear]: hasVariant(
            $state,
            "bottomTear",
            "bottomTear"
          ),
          [sty.navigationBarcolor_midnight]: hasVariant(
            $state,
            "color",
            "midnight"
          ),
          [sty.navigationBareffectVisible]: hasVariant(
            $state,
            "effectVisible",
            "effectVisible"
          ),
          [sty.navigationBarshadow]: hasVariant($state, "shadow", "shadow")
        })}
        closeButton={
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__nxp70)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"none"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            src={"https://static1.plasmic.app/close.svg"}
          />
        }
        itemsGap={8}
        menuItems={
          <React.Fragment>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__67C2x,
                projectcss.__wab_text,
                sty.link__tvF
              )}
              component={Link}
              href={"/"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Home"}
            </PlasmicLink__>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__67C2x,
                projectcss.__wab_text,
                sty.link__aqx6U
              )}
              component={Link}
              href={"/"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"About"}
            </PlasmicLink__>
            <PlasmicLink__
              className={classNames(
                projectcss.all,
                projectcss.a,
                projectcss.a__67C2x,
                projectcss.__wab_text,
                sty.link__xgET
              )}
              component={Link}
              href={"/"}
              legacyBehavior={false}
              platform={"nextjs"}
            >
              {"Contact"}
            </PlasmicLink__>
          </React.Fragment>
        }
        openButton={
          <PlasmicImg__
            alt={""}
            className={classNames(sty.img__yKhTs)}
            displayHeight={"auto"}
            displayMaxHeight={"none"}
            displayMaxWidth={"none"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"auto"}
            src={"https://static1.plasmic.app/menu.svg"}
          />
        }
        responsiveBreakpoint={
          hasVariant(globalVariants, "screen", "mobile") ? 640 : 768
        }
      />

      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      />
    </TornSection>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "navigationBar", "freeBox"],
  navigationBar: ["navigationBar"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof TornSection;
  navigationBar: typeof NavigationBar;
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavBanner__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavBanner__VariantsArgs;
    args?: PlasmicNavBanner__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicNavBanner__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicNavBanner__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNavBanner__ArgProps,
          internalVariantPropNames: PlasmicNavBanner__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavBanner__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavBanner";
  } else {
    func.displayName = `PlasmicNavBanner.${nodeName}`;
  }
  return func;
}

export const PlasmicNavBanner = Object.assign(
  // Top-level PlasmicNavBanner renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navigationBar: makeNodeComponent("navigationBar"),
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicNavBanner
    internalVariantProps: PlasmicNavBanner__VariantProps,
    internalArgProps: PlasmicNavBanner__ArgProps
  }
);

export default PlasmicNavBanner;
/* prettier-ignore-end */
