/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 67C2x4VH9CGyuASG98L3XF
// Component: KestoklH4saO

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: wLGJ71B22wJH/component
import { NoiseOverlay } from "@/components/plasmic-components/NoiseOverlay"; // plasmic-import: GohQkMFtGYyn/codeComponent
import { GradientBlob } from "@/components/plasmic-components/GradientBlob"; // plasmic-import: e8qsCr99-93Q/codeComponent
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/projectcss
import sty from "./PlasmicStyleGuide.module.css"; // plasmic-import: KestoklH4saO/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: 2Ox0yRYYMfoI/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: G6S5umLx_RKu/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicStyleGuide__VariantMembers = {};
export type PlasmicStyleGuide__VariantsArgs = {};
type VariantPropType = keyof PlasmicStyleGuide__VariantsArgs;
export const PlasmicStyleGuide__VariantProps = new Array<VariantPropType>();

export type PlasmicStyleGuide__ArgsType = {};
type ArgPropType = keyof PlasmicStyleGuide__ArgsType;
export const PlasmicStyleGuide__ArgProps = new Array<ArgPropType>();

export type PlasmicStyleGuide__OverridesType = {
  root?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  noiseOverlay?: Flex__<typeof NoiseOverlay>;
  freeBox2?: Flex__<"div">;
  gradientBlob?: Flex__<typeof GradientBlob>;
};

export interface DefaultStyleGuideProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicStyleGuide__RenderFunc(props: {
  variants: PlasmicStyleGuide__VariantsArgs;
  args: PlasmicStyleGuide__ArgsType;
  overrides: PlasmicStyleGuide__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <Button
            className={classNames("__wab_instance", sty.button__lgSr)}
            effect={
              <div
                data-plasmic-name={"freeBox"}
                data-plasmic-override={overrides.freeBox}
                className={classNames(projectcss.all, sty.freeBox)}
              >
                <NoiseOverlay
                  data-plasmic-name={"noiseOverlay"}
                  data-plasmic-override={overrides.noiseOverlay}
                  animate={true}
                  className={classNames("__wab_instance", sty.noiseOverlay)}
                />
              </div>
            }
          />

          <Button
            className={classNames("__wab_instance", sty.button___9Tay7)}
            effect={
              <React.Fragment>
                <div
                  data-plasmic-name={"freeBox2"}
                  data-plasmic-override={overrides.freeBox2}
                  className={classNames(projectcss.all, sty.freeBox2)}
                />

                <GradientBlob
                  data-plasmic-name={"gradientBlob"}
                  data-plasmic-override={overrides.gradientBlob}
                  blobCount={8}
                  className={classNames("__wab_instance", sty.gradientBlob)}
                  color1={true ? "#FFAB7B" : undefined}
                  color2={true ? "#295037" : undefined}
                  color3={true ? "#FF6A50" : undefined}
                  color4={true ? "#52A159" : undefined}
                />
              </React.Fragment>
            }
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "noiseOverlay", "freeBox2", "gradientBlob"],
  freeBox: ["freeBox", "noiseOverlay"],
  noiseOverlay: ["noiseOverlay"],
  freeBox2: ["freeBox2"],
  gradientBlob: ["gradientBlob"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  noiseOverlay: typeof NoiseOverlay;
  freeBox2: "div";
  gradientBlob: typeof GradientBlob;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStyleGuide__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStyleGuide__VariantsArgs;
    args?: PlasmicStyleGuide__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicStyleGuide__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicStyleGuide__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicStyleGuide__ArgProps,
          internalVariantPropNames: PlasmicStyleGuide__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStyleGuide__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStyleGuide";
  } else {
    func.displayName = `PlasmicStyleGuide.${nodeName}`;
  }
  return func;
}

export const PlasmicStyleGuide = Object.assign(
  // Top-level PlasmicStyleGuide renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    noiseOverlay: makeNodeComponent("noiseOverlay"),
    freeBox2: makeNodeComponent("freeBox2"),
    gradientBlob: makeNodeComponent("gradientBlob"),

    // Metadata about props expected for PlasmicStyleGuide
    internalVariantProps: PlasmicStyleGuide__VariantProps,
    internalArgProps: PlasmicStyleGuide__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/style-guide",
      pagePath: "/style-guide",
      params: {},
      query: {}
    })
  }
);

export default PlasmicStyleGuide;
/* prettier-ignore-end */
