/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 67C2x4VH9CGyuASG98L3XF
// Component: 6RLcIVBSHW0n

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { CmsPaginationButton } from "@/components/plasmic-components/CmsPagination"; // plasmic-import: VZghBDqwvaCo/codeComponent
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/projectcss
import sty from "./PlasmicPageButton.module.css"; // plasmic-import: 6RLcIVBSHW0n/css

createPlasmicElementProxy;

export type PlasmicPageButton__VariantMembers = {
  isActive: "isActive";
};
export type PlasmicPageButton__VariantsArgs = {
  isActive?: SingleBooleanChoiceArg<"isActive">;
};
type VariantPropType = keyof PlasmicPageButton__VariantsArgs;
export const PlasmicPageButton__VariantProps = new Array<VariantPropType>(
  "isActive"
);

export type PlasmicPageButton__ArgsType = { pageNumber?: number };
type ArgPropType = keyof PlasmicPageButton__ArgsType;
export const PlasmicPageButton__ArgProps = new Array<ArgPropType>("pageNumber");

export type PlasmicPageButton__OverridesType = {
  root?: Flex__<"div">;
  cmsPaginationButton?: Flex__<typeof CmsPaginationButton>;
};

export interface DefaultPageButtonProps {
  pageNumber?: number;
  isActive?: SingleBooleanChoiceArg<"isActive">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicPageButton__RenderFunc(props: {
  variants: PlasmicPageButton__VariantsArgs;
  args: PlasmicPageButton__ArgsType;
  overrides: PlasmicPageButton__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          pageNumber: 1
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "isActive",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.isActive
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root,
        { [sty.rootisActive]: hasVariant($state, "isActive", "isActive") }
      )}
    >
      <CmsPaginationButton
        data-plasmic-name={"cmsPaginationButton"}
        data-plasmic-override={overrides.cmsPaginationButton}
        className={classNames("__wab_instance", sty.cmsPaginationButton, {
          [sty.cmsPaginationButtonisActive]: hasVariant(
            $state,
            "isActive",
            "isActive"
          )
        })}
        isActive={hasVariant($state, "isActive", "isActive") ? true : undefined}
      >
        <React.Fragment>
          {(() => {
            try {
              return $props.pageNumber;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return "1";
              }
              throw e;
            }
          })()}
        </React.Fragment>
      </CmsPaginationButton>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "cmsPaginationButton"],
  cmsPaginationButton: ["cmsPaginationButton"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  cmsPaginationButton: typeof CmsPaginationButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPageButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPageButton__VariantsArgs;
    args?: PlasmicPageButton__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicPageButton__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicPageButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicPageButton__ArgProps,
          internalVariantPropNames: PlasmicPageButton__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicPageButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPageButton";
  } else {
    func.displayName = `PlasmicPageButton.${nodeName}`;
  }
  return func;
}

export const PlasmicPageButton = Object.assign(
  // Top-level PlasmicPageButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    cmsPaginationButton: makeNodeComponent("cmsPaginationButton"),

    // Metadata about props expected for PlasmicPageButton
    internalVariantProps: PlasmicPageButton__VariantProps,
    internalArgProps: PlasmicPageButton__ArgProps
  }
);

export default PlasmicPageButton;
/* prettier-ignore-end */
