/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 67C2x4VH9CGyuASG98L3XF
// Component: FuUP13USuDR8

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import NavBanner from "../../NavBanner"; // plasmic-import: uEuM32AhsVsN/component
import { FloatingElement } from "@/components/plasmic-components/FloatingElement"; // plasmic-import: VhAhx6UYzzRr/codeComponent
import { OffsetShape } from "@/components/plasmic-components/OffsetShape"; // plasmic-import: 6iLg6RvlDLn6/codeComponent
import { OffsetImage } from "@/components/plasmic-components/OffsetImage"; // plasmic-import: bIanIbIW8b7U/codeComponent
import Button from "../../Button"; // plasmic-import: wLGJ71B22wJH/component
import { OffsetCMYK } from "@/components/plasmic-components/OffsetCMYK"; // plasmic-import: W6F38AxYTSP7/codeComponent
import { NextImage } from "@/components/plasmic-components/NextImage"; // plasmic-import: 6-H-ZX-IJsr_/codeComponent
import MarqueeScroll from "../../MarqueeScroll"; // plasmic-import: p7cDk5onbOfu/component
import { InkBleed } from "@/components/plasmic-components/InkBleed"; // plasmic-import: x-cwBn9SIvTe/codeComponent
import { CmsPaginationContext } from "@/components/plasmic-components/CmsPagination"; // plasmic-import: XQkM4MEcOLl0/codeComponent
import { CmsQueryRepeater } from "@plasmicpkgs/plasmic-cms";
import { TornSection } from "@/components/plasmic-components/TornSection"; // plasmic-import: 8y_E0U1V1ob-/codeComponent
import { CmsRowField } from "@plasmicpkgs/plasmic-cms";
import { NoiseOverlay } from "@/components/plasmic-components/NoiseOverlay"; // plasmic-import: GohQkMFtGYyn/codeComponent
import { ScotchTape } from "@/components/plasmic-components/ScotchTape"; // plasmic-import: TbfB48S8CS8c/codeComponent
import { Shimmer } from "@/components/plasmic-components/Shimmer"; // plasmic-import: dBSvAg8mx3HD/codeComponent
import { CmsPaginationControls } from "@/components/plasmic-components/CmsPagination"; // plasmic-import: Nj2KT56kVjVw/codeComponent
import PageButton from "../../PageButton"; // plasmic-import: 6RLcIVBSHW0n/component
import { HalftoneMask } from "@/components/plasmic-components/HalftoneMask"; // plasmic-import: tq6byP_N1Ydj/codeComponent
import MarqueeScroll2 from "../../MarqueeScroll2"; // plasmic-import: a2tFCAaUQuGy/component
import Footer from "../../Footer"; // plasmic-import: jjWjxw2fIQP_/component
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 67C2x4VH9CGyuASG98L3XF/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import sty from "./PlasmicHomepage.module.css"; // plasmic-import: FuUP13USuDR8/css

import RegistrationMarkTargetSvg2Icon from "./icons/PlasmicIcon__RegistrationMarkTargetSvg2"; // plasmic-import: eGWLBGxB6lSY/icon
import RegistrationMarkCornerSvg2Icon from "./icons/PlasmicIcon__RegistrationMarkCornerSvg2"; // plasmic-import: S_mhq_tZ6KnU/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: 2Ox0yRYYMfoI/icon
import CirclesparkleSvgIcon from "./icons/PlasmicIcon__CirclesparkleSvg"; // plasmic-import: 9fph0KMRmqAr/icon
import EyeconSvgIcon from "./icons/PlasmicIcon__EyeconSvg"; // plasmic-import: qwQ4br4oCQfg/icon
import ArrowRightSvgIcon from "./icons/PlasmicIcon__ArrowRightSvg"; // plasmic-import: 0vNaQ1KvdrHQ/icon
import ArrowLeftSvgIcon from "./icons/PlasmicIcon__ArrowLeftSvg"; // plasmic-import: 1pIw_X8xb4RU/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  navBanner?: Flex__<typeof NavBanner>;
  columns?: Flex__<"div">;
  h4?: Flex__<"h4">;
  freeBox5?: Flex__<"div">;
  freeBox6?: Flex__<"div">;
  marqueeScroll?: Flex__<typeof MarqueeScroll>;
  section?: Flex__<"section">;
  cmsPaginationContext?: Flex__<typeof CmsPaginationContext>;
  cmsDataFetcher?: Flex__<typeof CmsQueryRepeater>;
  freeBox4?: Flex__<"div">;
  freeBox3?: Flex__<"div">;
  cmsPaginationControls?: Flex__<typeof CmsPaginationControls>;
  pageButton?: Flex__<typeof PageButton>;
  marqueeScroll2?: Flex__<typeof MarqueeScroll2>;
  footer?: Flex__<typeof Footer>;
};

export interface DefaultHomepageProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const pageMetadata = generateDynamicMetadata(
    wrapQueriesWithLoadingProxy({}),
    $ctx as PageCtx
  );

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_67C2x4VH9CGyuASG98L3XF",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.root
          )}
        >
          <NavBanner
            data-plasmic-name={"navBanner"}
            data-plasmic-override={overrides.navBanner}
            bottomTear={true}
            className={classNames("__wab_instance", sty.navBanner)}
            color={"midnight"}
            effectVisible={true}
          />

          <div
            data-plasmic-name={"columns"}
            data-plasmic-override={overrides.columns}
            className={classNames("all", sty.columns)}
          >
            <div className={classNames("all", sty.column___2GzTv)}>
              <div className={classNames("all", sty.freeBox__rt7Me)}>
                <h4
                  data-plasmic-name={"h4"}
                  data-plasmic-override={overrides.h4}
                  className={classNames(
                    "all",
                    "h4",
                    "h4__67C2x",
                    "__wab_text",
                    sty.h4
                  )}
                >
                  {"hello, my name is"}
                </h4>
              </div>
              <h1
                className={classNames(
                  "all",
                  "h1",
                  "h1__67C2x",
                  "__wab_text",
                  sty.h1___2PyZv
                )}
              >
                {"steff bradley"}
              </h1>
              <div className={classNames("all", "__wab_text", sty.text__wlB8S)}>
                <React.Fragment>
                  <React.Fragment>{"i'm a "}</React.Fragment>
                  <span
                    className={
                      "plasmic_default__all plasmic_default__span plasmic_default__span__67C2x"
                    }
                    style={{
                      fontWeight: 700,
                      color: "var(--token-5QKIfNB0tRzE)"
                    }}
                  >
                    {"designer"}
                  </span>
                  <React.Fragment>{", "}</React.Fragment>
                  <span
                    className={
                      "plasmic_default__all plasmic_default__span plasmic_default__span__67C2x"
                    }
                    style={{
                      fontWeight: 700,
                      color: "var(--token-aXuLypa7xfma)"
                    }}
                  >
                    {"artist"}
                  </span>
                  <React.Fragment>{", & "}</React.Fragment>
                  <span
                    className={
                      "plasmic_default__all plasmic_default__span plasmic_default__span__67C2x"
                    }
                    style={{
                      fontWeight: 700,
                      color: "var(--token-B34tJ4Y-Hjpw)"
                    }}
                  >
                    {"web developer"}
                  </span>
                  <React.Fragment>
                    {
                      "; always experimenting & always learning\ni work with motion, interactivity, design engineering, and systems"
                    }
                  </React.Fragment>
                </React.Fragment>
              </div>
              <FloatingElement
                className={classNames(
                  "__wab_instance",
                  sty.floatingElement__phqx3
                )}
              >
                <OffsetShape
                  className={classNames(
                    "__wab_instance",
                    sty.offsetShape__vCwh
                  )}
                  colorA={true ? "#FF6A50" : undefined}
                  colorB={true ? "#CEBEE3" : undefined}
                  jitter={8}
                  offsetX={6}
                  offsetY={-3}
                  texture={"halftone"}
                  textureStep={3}
                >
                  <RegistrationMarkTargetSvg2Icon
                    className={classNames("all", sty.svg__hwk3K)}
                    role={"img"}
                  />
                </OffsetShape>
              </FloatingElement>
              <FloatingElement
                className={classNames(
                  "__wab_instance",
                  sty.floatingElement__zri9C
                )}
              >
                <OffsetShape
                  className={classNames(
                    "__wab_instance",
                    sty.offsetShape__kty4F
                  )}
                  colorA={true ? "#00427F" : undefined}
                  colorB={true ? "#DDEA44" : undefined}
                  texture={"halftone"}
                  textureStep={3}
                >
                  <RegistrationMarkCornerSvg2Icon
                    className={classNames("all", sty.svg__qKs5S)}
                    role={"img"}
                  />
                </OffsetShape>
              </FloatingElement>
              <OffsetImage
                className={classNames("__wab_instance", sty.offsetImage__butHq)}
                colorA={true ? "#52A159" : undefined}
                colorB={true ? "#CEBEE3" : undefined}
                imageContrast={3}
                jitter={0.3}
                offsetX={2}
                offsetY={2}
                slotA={
                  <Button
                    className={classNames("__wab_instance", sty.button__fgFa1)}
                    color={"blue"}
                    disabled={false}
                    effect={
                      <div
                        data-plasmic-name={"freeBox5"}
                        data-plasmic-override={overrides.freeBox5}
                        className={classNames("all", sty.freeBox5)}
                      />
                    }
                    end={
                      <CirclesparkleSvgIcon
                        className={classNames("all", sty.svg__v3HEj)}
                        role={"img"}
                      />
                    }
                    iconEnd={true}
                    label={
                      <div
                        className={classNames(
                          "all",
                          "__wab_text",
                          sty.text__vbMxN
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return "contact me";
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    }
                  />
                }
                slotB={
                  <div
                    data-plasmic-name={"freeBox6"}
                    data-plasmic-override={overrides.freeBox6}
                    className={classNames("all", sty.freeBox6)}
                  />
                }
                texture={"noise"}
                textureContrast={80}
                textureHoverEnabled={false}
                textureStep={1}
                tintSlots={true}
              />
            </div>
            <div className={classNames("all", sty.column___77LZa)}>
              <FloatingElement
                animationAmplitude={40}
                className={classNames(
                  "__wab_instance",
                  sty.floatingElement__kBxv9
                )}
              >
                <OffsetCMYK
                  blendMode={"darken"}
                  className={classNames(
                    "__wab_instance",
                    sty.offsetCmyk__sTgZh
                  )}
                  colorC={true ? "#CEBEE3" : undefined}
                  colorK={true ? "#00427F" : undefined}
                  colorM={true ? "#FF6A50" : undefined}
                  colorY={true ? "#DDEA44" : undefined}
                  texture={"noise"}
                  textureContrast={70}
                  textureHoverEnabled={false}
                  textureStep={1}
                >
                  <NextImage
                    alt={""}
                    className={classNames("__wab_instance", sty.image__uPw9)}
                    src={"/plasmic/toothmonster/images/toothcontactGif.gif"}
                  />
                </OffsetCMYK>
              </FloatingElement>
            </div>
          </div>
          <MarqueeScroll
            data-plasmic-name={"marqueeScroll"}
            data-plasmic-override={overrides.marqueeScroll}
            className={classNames("__wab_instance", sty.marqueeScroll)}
          />

          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames("all", sty.section)}
          >
            <div className={classNames("all", sty.freeBox__jkuRf)}>
              <InkBleed
                bleedColor={true ? "#52A159" : undefined}
                className={classNames("__wab_instance", sty.inkBleed__c3Ucr)}
                noiseFrequency={2}
                softness={10}
                spread={2}
              >
                <h1
                  className={classNames(
                    "all",
                    "h1",
                    "h1__67C2x",
                    "__wab_text",
                    sty.h1__v75DS
                  )}
                >
                  {"archives"}
                </h1>
              </InkBleed>
              <div className={classNames("all", "__wab_text", sty.text__os7Jm)}>
                {"a portfolio of case studies"}
              </div>
            </div>
            <div className={classNames("all", sty.freeBox__mlmSe)}>
              <CmsPaginationContext
                data-plasmic-name={"cmsPaginationContext"}
                data-plasmic-override={overrides.cmsPaginationContext}
                className={classNames(
                  "__wab_instance",
                  sty.cmsPaginationContext
                )}
                databaseId={"1XTea8SGxneQLsfTFD3nDB"}
                databaseToken={
                  "8QLNduGOr5ivOEyTRMYivo9hizvASFYdD1muqeQuUh2IbycxLdMaWmeMe43ZjpENSsONuy3cjlT4EDwA"
                }
                pageSize={
                  hasVariant(globalVariants, "screen", "mobile") ? 1 : 2
                }
                table={"caseStudyTitle"}
              >
                <DataCtxReader__>
                  {$ctx => (
                    <React.Fragment>
                      <CmsQueryRepeater
                        data-plasmic-name={"cmsDataFetcher"}
                        data-plasmic-override={overrides.cmsDataFetcher}
                        className={classNames(
                          "__wab_instance",
                          sty.cmsDataFetcher
                        )}
                        desc={false}
                        emptyMessage={
                          <DataCtxReader__>
                            {$ctx => (
                              <div
                                className={classNames(
                                  "all",
                                  "__wab_text",
                                  sty.text__oc6Ad
                                )}
                              >
                                {"No matching published entries found."}
                              </div>
                            )}
                          </DataCtxReader__>
                        }
                        forceEmptyState={false}
                        forceLoadingState={false}
                        limit={(() => {
                          try {
                            return $ctx.paginationCtx.pageSize;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return 2;
                            }
                            throw e;
                          }
                        })()}
                        loadingMessage={
                          <DataCtxReader__>
                            {$ctx => (
                              <React.Fragment>
                                <Shimmer
                                  baseColor={true ? "#EDE9E3" : undefined}
                                  className={classNames(
                                    "__wab_instance",
                                    sty.shimmer__fu31N
                                  )}
                                  highlightColor={true ? "#CEBEE3" : undefined}
                                />

                                <Shimmer
                                  baseColor={true ? "#EDE9E3" : undefined}
                                  className={classNames(
                                    "__wab_instance",
                                    sty.shimmer__yVs7W
                                  )}
                                  highlightColor={true ? "#CEBEE3" : undefined}
                                />
                              </React.Fragment>
                            )}
                          </DataCtxReader__>
                        }
                        mode={"rows"}
                        noAutoRepeat={false}
                        noLayout={false}
                        offset={$ctx.paginationCtx.offset}
                        orderBy={"caseStudyYear"}
                        table={"caseStudyTitle"}
                        useDraft={false}
                      >
                        <DataCtxReader__>
                          {$ctx => (
                            <div
                              className={classNames("all", sty.freeBox__o20Od)}
                            >
                              <TornSection
                                background={
                                  <React.Fragment>
                                    <NoiseOverlay
                                      className={classNames(
                                        "__wab_instance",
                                        sty.noiseOverlay__dfJt
                                      )}
                                      color={true ? "#504C57" : undefined}
                                    />

                                    <div
                                      className={classNames(
                                        "all",
                                        sty.freeBox___5QeFc
                                      )}
                                    />
                                  </React.Fragment>
                                }
                                className={classNames(
                                  "__wab_instance",
                                  sty.tornSection__xeClH
                                )}
                                tornBottom={true}
                                tornBottomDepthPx={4}
                                tornTop={false}
                              >
                                <div
                                  className={classNames(
                                    "all",
                                    sty.freeBox__u892S
                                  )}
                                >
                                  <EyeconSvgIcon
                                    className={classNames(
                                      "all",
                                      sty.svg__g3NRr
                                    )}
                                    role={"img"}
                                  />

                                  <CmsRowField
                                    className={classNames(
                                      "__wab_instance",
                                      sty.cmsEntryField__uQQx
                                    )}
                                    field={"caseStudyYear"}
                                    themeResetClassName={classNames(
                                      "root_reset_67C2x4VH9CGyuASG98L3XF",
                                      "root_reset_67C2x4VH9CGyuASG98L3XF_tags",
                                      "plasmic_default_styles",
                                      "plasmic_mixins",
                                      styleTokensClassNames
                                    )}
                                  />
                                </div>
                              </TornSection>
                              <div
                                className={classNames(
                                  "all",
                                  sty.freeBox__soZho
                                )}
                              >
                                <OffsetCMYK
                                  blendMode={"multiply"}
                                  channelContrast={1.2}
                                  className={classNames(
                                    "__wab_instance",
                                    sty.offsetCmyk__jr5Hn
                                  )}
                                  colorC={true ? "#CEBEE3" : undefined}
                                  colorK={true ? "#00427F" : undefined}
                                  colorM={true ? "#FF6A50" : undefined}
                                  colorY={true ? "#DDEA44" : undefined}
                                  interaction={"inverse"}
                                  jitter={2}
                                  offsetX={0.3}
                                  offsetY={0.2}
                                  texture={"halftone"}
                                  textureContrast={90}
                                  textureHoverEnabled={false}
                                  textureStep={3}
                                >
                                  <NextImage
                                    alt={""}
                                    className={classNames(
                                      "__wab_instance",
                                      sty.image__tPqGa
                                    )}
                                    objectFit={"cover"}
                                    src={
                                      $ctx.plasmicCmsCaseStudyTitleItem.data
                                        .caseStudyCardImg.url
                                    }
                                  />
                                </OffsetCMYK>
                                <div
                                  className={classNames(
                                    "all",
                                    sty.freeBox__gn4Il
                                  )}
                                />
                              </div>
                              <TornSection
                                background={
                                  <React.Fragment>
                                    <NoiseOverlay
                                      className={classNames(
                                        "__wab_instance",
                                        sty.noiseOverlay__c0Oc
                                      )}
                                      color={true ? "#EDE9E3" : undefined}
                                    />

                                    <div
                                      className={classNames(
                                        "all",
                                        sty.freeBox___71K9A
                                      )}
                                    />
                                  </React.Fragment>
                                }
                                className={classNames(
                                  "__wab_instance",
                                  sty.tornSection___3PrAn
                                )}
                                tornBottom={false}
                                tornTop={true}
                                tornTopDepthPx={4}
                              >
                                <div
                                  className={classNames(
                                    "all",
                                    sty.freeBox__feoX5
                                  )}
                                >
                                  <div
                                    className={classNames(
                                      "all",
                                      sty.freeBox__fmcLb
                                    )}
                                  >
                                    <div
                                      className={classNames(
                                        "all",
                                        sty.freeBox__xFfEu
                                      )}
                                    >
                                      <InkBleed
                                        bleedColor={
                                          true ? "#504C57" : undefined
                                        }
                                        className={classNames(
                                          "__wab_instance",
                                          sty.inkBleed___28Jzj
                                        )}
                                        noiseFrequency={1}
                                        spread={1}
                                      >
                                        <CmsRowField
                                          className={classNames(
                                            "__wab_instance",
                                            sty.cmsEntryField__pmeDw
                                          )}
                                          field={"caseStudyTitle"}
                                          themeResetClassName={classNames(
                                            "root_reset_67C2x4VH9CGyuASG98L3XF",
                                            "root_reset_67C2x4VH9CGyuASG98L3XF_tags",
                                            "plasmic_default_styles",
                                            "plasmic_mixins",
                                            styleTokensClassNames
                                          )}
                                        />
                                      </InkBleed>
                                      <CmsRowField
                                        className={classNames(
                                          "__wab_instance",
                                          sty.cmsEntryField__ddsi
                                        )}
                                        field={"caseStudyDesc"}
                                        themeResetClassName={classNames(
                                          "root_reset_67C2x4VH9CGyuASG98L3XF",
                                          "root_reset_67C2x4VH9CGyuASG98L3XF_tags",
                                          "plasmic_default_styles",
                                          "plasmic_mixins",
                                          styleTokensClassNames
                                        )}
                                      />
                                    </div>
                                  </div>
                                  {(() => {
                                    try {
                                      return true;
                                    } catch (e) {
                                      if (
                                        e instanceof TypeError ||
                                        e?.plasmicType ===
                                          "PlasmicUndefinedDataError"
                                      ) {
                                        return true;
                                      }
                                      throw e;
                                    }
                                  })() ? (
                                    <div
                                      className={classNames(
                                        "all",
                                        sty.freeBox__sT4Ma
                                      )}
                                    >
                                      {(() => {
                                        try {
                                          return true;
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return true;
                                          }
                                          throw e;
                                        }
                                      })() ? (
                                        <ScotchTape
                                          className={classNames(
                                            "__wab_instance",
                                            sty.scotchTape__lsJyl
                                          )}
                                        >
                                          {(() => {
                                            try {
                                              return !!$ctx
                                                .plasmicCmsCaseStudyTitleItem
                                                .data.caseStudyStat1;
                                            } catch (e) {
                                              if (
                                                e instanceof TypeError ||
                                                e?.plasmicType ===
                                                  "PlasmicUndefinedDataError"
                                              ) {
                                                return true;
                                              }
                                              throw e;
                                            }
                                          })() ? (
                                            <div
                                              className={classNames(
                                                "all",
                                                sty.freeBox__uLe3I
                                              )}
                                            >
                                              <InkBleed
                                                bleedColor={(() => {
                                                  try {
                                                    return $ctx
                                                      .plasmicCmsCaseStudyTitleItem
                                                      .data.caseStudyColor;
                                                  } catch (e) {
                                                    if (
                                                      e instanceof TypeError ||
                                                      e?.plasmicType ===
                                                        "PlasmicUndefinedDataError"
                                                    ) {
                                                      return "var(--token-tt4LcQz9DuF0)";
                                                    }
                                                    throw e;
                                                  }
                                                })()}
                                                className={classNames(
                                                  "__wab_instance",
                                                  sty.inkBleed__e5O2L
                                                )}
                                                noiseFrequency={1}
                                                spread={0.2}
                                              >
                                                <div
                                                  className={classNames(
                                                    "all",
                                                    "__wab_text",
                                                    sty.text___2GmT7
                                                  )}
                                                  style={{
                                                    color:
                                                      $ctx
                                                        .plasmicCmsCaseStudyTitleItem
                                                        .data.caseStudyColor
                                                  }}
                                                >
                                                  <React.Fragment>
                                                    {
                                                      $ctx
                                                        .plasmicCmsCaseStudyTitleItem
                                                        .data.caseStudyStat1[
                                                        "1statNum"
                                                      ]
                                                    }
                                                  </React.Fragment>
                                                </div>
                                              </InkBleed>
                                              <div
                                                className={classNames(
                                                  "all",
                                                  "__wab_text",
                                                  sty.text__oEz86
                                                )}
                                              >
                                                <React.Fragment>
                                                  {
                                                    $ctx
                                                      .plasmicCmsCaseStudyTitleItem
                                                      .data.caseStudyStat1[
                                                      "1statLabel"
                                                    ]
                                                  }
                                                </React.Fragment>
                                              </div>
                                            </div>
                                          ) : null}
                                        </ScotchTape>
                                      ) : null}
                                      <ScotchTape
                                        className={classNames(
                                          "__wab_instance",
                                          sty.scotchTape__gkSoL
                                        )}
                                        rotation={2}
                                      >
                                        {(() => {
                                          try {
                                            return !!$ctx
                                              .plasmicCmsCaseStudyTitleItem.data
                                              .caseStudyStat2;
                                          } catch (e) {
                                            if (
                                              e instanceof TypeError ||
                                              e?.plasmicType ===
                                                "PlasmicUndefinedDataError"
                                            ) {
                                              return true;
                                            }
                                            throw e;
                                          }
                                        })() ? (
                                          <div
                                            className={classNames(
                                              "all",
                                              sty.freeBox__jLey1
                                            )}
                                          >
                                            <InkBleed
                                              bleedColor={(() => {
                                                try {
                                                  return $ctx
                                                    .plasmicCmsCaseStudyTitleItem
                                                    .data.caseStudyColor;
                                                } catch (e) {
                                                  if (
                                                    e instanceof TypeError ||
                                                    e?.plasmicType ===
                                                      "PlasmicUndefinedDataError"
                                                  ) {
                                                    return "var(--token-tt4LcQz9DuF0)";
                                                  }
                                                  throw e;
                                                }
                                              })()}
                                              className={classNames(
                                                "__wab_instance",
                                                sty.inkBleed__mAanX
                                              )}
                                              noiseFrequency={1}
                                              spread={0.2}
                                            >
                                              <div
                                                className={classNames(
                                                  "all",
                                                  "__wab_text",
                                                  sty.text__ejBwm
                                                )}
                                                style={{
                                                  color:
                                                    $ctx
                                                      .plasmicCmsCaseStudyTitleItem
                                                      .data.caseStudyColor
                                                }}
                                              >
                                                <React.Fragment>
                                                  {
                                                    $ctx
                                                      .plasmicCmsCaseStudyTitleItem
                                                      .data.caseStudyStat2[
                                                      "2statNum"
                                                    ]
                                                  }
                                                </React.Fragment>
                                              </div>
                                            </InkBleed>
                                            <div
                                              className={classNames(
                                                "all",
                                                "__wab_text",
                                                sty.text__krsGt
                                              )}
                                            >
                                              <React.Fragment>
                                                {
                                                  $ctx
                                                    .plasmicCmsCaseStudyTitleItem
                                                    .data.caseStudyStat2[
                                                    "2statLabel"
                                                  ]
                                                }
                                              </React.Fragment>
                                            </div>
                                          </div>
                                        ) : null}
                                      </ScotchTape>
                                    </div>
                                  ) : null}
                                  <div
                                    className={classNames(
                                      "all",
                                      sty.freeBox___41QhX
                                    )}
                                  >
                                    <OffsetImage
                                      blendMode={"overlay"}
                                      className={classNames(
                                        "__wab_instance",
                                        sty.offsetImage__c47R
                                      )}
                                      colorA={(() => {
                                        try {
                                          return $ctx
                                            .plasmicCmsCaseStudyTitleItem.data
                                            .caseStudyColor;
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return "var(--token-tt4LcQz9DuF0)";
                                          }
                                          throw e;
                                        }
                                      })()}
                                      colorB={(() => {
                                        try {
                                          return $ctx
                                            .plasmicCmsCaseStudyTitleItem.data
                                            .caseStudyAccentColor;
                                        } catch (e) {
                                          if (
                                            e instanceof TypeError ||
                                            e?.plasmicType ===
                                              "PlasmicUndefinedDataError"
                                          ) {
                                            return "var(--token-doCHQ9G8_OsB)";
                                          }
                                          throw e;
                                        }
                                      })()}
                                      imageContrast={0}
                                      interaction={
                                        hasVariant(
                                          globalVariants,
                                          "screen",
                                          "mobile"
                                        )
                                          ? "click"
                                          : "hover"
                                      }
                                      jitter={0.3}
                                      offsetX={2}
                                      offsetY={2}
                                      slotA={
                                        <Button
                                          className={classNames(
                                            "__wab_instance",
                                            sty.button__dfAjz
                                          )}
                                          color={"blue"}
                                          disabled={false}
                                          effect={
                                            <div
                                              data-plasmic-name={"freeBox4"}
                                              data-plasmic-override={
                                                overrides.freeBox4
                                              }
                                              className={classNames(
                                                "all",
                                                sty.freeBox4
                                              )}
                                            />
                                          }
                                          end={
                                            <ArrowRightSvgIcon
                                              className={classNames(
                                                "all",
                                                sty.svg__j0Xov
                                              )}
                                              role={"img"}
                                            />
                                          }
                                          iconEnd={true}
                                          label={
                                            <div
                                              className={classNames(
                                                "all",
                                                "__wab_text",
                                                sty.text__zmmpr
                                              )}
                                            >
                                              {"case study"}
                                            </div>
                                          }
                                          linkTo={`/portfolio/${(() => {
                                            try {
                                              return `"/portfolio/" + $ctx.plasmicCmsCaseStudyTitleItem.data.caseStudySlug`;
                                            } catch (e) {
                                              if (
                                                e instanceof TypeError ||
                                                e?.plasmicType ===
                                                  "PlasmicUndefinedDataError"
                                              ) {
                                                return undefined;
                                              }
                                              throw e;
                                            }
                                          })()}`}
                                        />
                                      }
                                      slotB={
                                        <div
                                          data-plasmic-name={"freeBox3"}
                                          data-plasmic-override={
                                            overrides.freeBox3
                                          }
                                          className={classNames(
                                            "all",
                                            sty.freeBox3
                                          )}
                                        />
                                      }
                                      texture={"noise"}
                                      textureContrast={80}
                                      textureHoverEnabled={false}
                                      textureStep={1}
                                      tintSlots={true}
                                    />
                                  </div>
                                </div>
                              </TornSection>
                            </div>
                          )}
                        </DataCtxReader__>
                      </CmsQueryRepeater>
                      <CmsPaginationControls
                        data-plasmic-name={"cmsPaginationControls"}
                        data-plasmic-override={overrides.cmsPaginationControls}
                        className={classNames(
                          "__wab_instance",
                          sty.cmsPaginationControls
                        )}
                        maxPageButtons={
                          hasVariant(globalVariants, "screen", "mobile")
                            ? 4
                            : undefined
                        }
                        nextButton={
                          <ArrowRightSvgIcon
                            className={classNames("all", sty.svg___4IaMu)}
                            role={"img"}
                          />
                        }
                        nextButtonInactive={
                          <ArrowRightSvgIcon
                            className={classNames("all", sty.svg__rtLfu)}
                            role={"img"}
                          />
                        }
                        pageButton={
                          <PageButton
                            data-plasmic-name={"pageButton"}
                            data-plasmic-override={overrides.pageButton}
                            className={classNames(
                              "__wab_instance",
                              sty.pageButton
                            )}
                          />
                        }
                        prevButton={
                          <ArrowLeftSvgIcon
                            className={classNames("all", sty.svg__kK1Qx)}
                            role={"img"}
                          />
                        }
                        prevButtonInactive={
                          <ArrowLeftSvgIcon
                            className={classNames("all", sty.svg__kwd8K)}
                            role={"img"}
                          />
                        }
                      />
                    </React.Fragment>
                  )}
                </DataCtxReader__>
              </CmsPaginationContext>
            </div>
            <div className={classNames("all", sty.freeBox__awWL)}>
              <HalftoneMask
                className={classNames(
                  "__wab_instance",
                  sty.halftoneMask__qkJjM
                )}
                color={true ? "#DDEA44" : undefined}
                contrast={80}
                imageContrast={-0.3}
              >
                <NextImage
                  alt={""}
                  className={classNames("__wab_instance", sty.image__jTA3)}
                  src={"/plasmic/toothmonster/images/sunraysGif.gif"}
                  width={250}
                />
              </HalftoneMask>
              <HalftoneMask
                angleIndex={1}
                className={classNames(
                  "__wab_instance",
                  sty.halftoneMask__tpFRq
                )}
                color={true ? "#FF6A50" : undefined}
                contrast={80}
                imageContrast={0.4}
              >
                <NextImage
                  alt={""}
                  className={classNames("__wab_instance", sty.image__zpiN2)}
                  src={"/plasmic/toothmonster/images/sunraysGif.gif"}
                  width={250}
                />
              </HalftoneMask>
            </div>
            <div className={classNames("all", sty.freeBox___4ElwX)}>
              <HalftoneMask
                className={classNames("__wab_instance", sty.halftoneMask__mLp1)}
                color={true ? "#CEBEE3" : undefined}
                contrast={80}
                imageContrast={-0.3}
              >
                <NextImage
                  alt={""}
                  className={classNames("__wab_instance", sty.image___2FQh)}
                  src={"/plasmic/toothmonster/images/flowerGif.gif"}
                  width={250}
                />
              </HalftoneMask>
              <HalftoneMask
                angleIndex={1}
                className={classNames(
                  "__wab_instance",
                  sty.halftoneMask__o9CWe
                )}
                color={true ? "#00427F" : undefined}
                contrast={80}
                imageContrast={0.4}
              >
                <NextImage
                  alt={""}
                  className={classNames("__wab_instance", sty.image__gdzFk)}
                  src={"/plasmic/toothmonster/images/flowerGif.gif"}
                  width={250}
                />
              </HalftoneMask>
            </div>
          </section>
          <MarqueeScroll2
            data-plasmic-name={"marqueeScroll2"}
            data-plasmic-override={overrides.marqueeScroll2}
            className={classNames("__wab_instance", sty.marqueeScroll2)}
          />

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBanner",
    "columns",
    "h4",
    "freeBox5",
    "freeBox6",
    "marqueeScroll",
    "section",
    "cmsPaginationContext",
    "cmsDataFetcher",
    "freeBox4",
    "freeBox3",
    "cmsPaginationControls",
    "pageButton",
    "marqueeScroll2",
    "footer"
  ],
  navBanner: ["navBanner"],
  columns: ["columns", "h4", "freeBox5", "freeBox6"],
  h4: ["h4"],
  freeBox5: ["freeBox5"],
  freeBox6: ["freeBox6"],
  marqueeScroll: ["marqueeScroll"],
  section: [
    "section",
    "cmsPaginationContext",
    "cmsDataFetcher",
    "freeBox4",
    "freeBox3",
    "cmsPaginationControls",
    "pageButton"
  ],
  cmsPaginationContext: [
    "cmsPaginationContext",
    "cmsDataFetcher",
    "freeBox4",
    "freeBox3",
    "cmsPaginationControls",
    "pageButton"
  ],
  cmsDataFetcher: ["cmsDataFetcher", "freeBox4", "freeBox3"],
  freeBox4: ["freeBox4"],
  freeBox3: ["freeBox3"],
  cmsPaginationControls: ["cmsPaginationControls", "pageButton"],
  pageButton: ["pageButton"],
  marqueeScroll2: ["marqueeScroll2"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBanner: typeof NavBanner;
  columns: "div";
  h4: "h4";
  freeBox5: "div";
  freeBox6: "div";
  marqueeScroll: typeof MarqueeScroll;
  section: "section";
  cmsPaginationContext: typeof CmsPaginationContext;
  cmsDataFetcher: typeof CmsQueryRepeater;
  freeBox4: "div";
  freeBox3: "div";
  cmsPaginationControls: typeof CmsPaginationControls;
  pageButton: typeof PageButton;
  marqueeScroll2: typeof MarqueeScroll2;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBanner: makeNodeComponent("navBanner"),
    columns: makeNodeComponent("columns"),
    h4: makeNodeComponent("h4"),
    freeBox5: makeNodeComponent("freeBox5"),
    freeBox6: makeNodeComponent("freeBox6"),
    marqueeScroll: makeNodeComponent("marqueeScroll"),
    section: makeNodeComponent("section"),
    cmsPaginationContext: makeNodeComponent("cmsPaginationContext"),
    cmsDataFetcher: makeNodeComponent("cmsDataFetcher"),
    freeBox4: makeNodeComponent("freeBox4"),
    freeBox3: makeNodeComponent("freeBox3"),
    cmsPaginationControls: makeNodeComponent("cmsPaginationControls"),
    pageButton: makeNodeComponent("pageButton"),
    marqueeScroll2: makeNodeComponent("marqueeScroll2"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/",
      pagePath: "/",
      params: {},
      query: {}
    })
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
