// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";
import GlobalContextsProvider from "../components/plasmic/toothmonster/PlasmicGlobalContextsProvider";

import { PlasmicHomepage } from "../components/plasmic/toothmonster/PlasmicHomepage";
import { useRouter } from "next/router";
import { PlasmicQueryDataProvider } from "@plasmicapp/react-web/lib/query";
import { EyeLoader } from "@/components/plasmic-components/EyeLoader";

// Floor on how long the splash stays up, so it's never just a flash on a fast
// hydrate.
const SPLASH_MIN_MS = 1200;

function Homepage() {
  // Rendered on the server, so it's part of the very first HTML the browser
  // paints — before React has hydrated. Flips true after the minimum splash
  // time has elapsed on the client, after which the overlay fades out.
  const [splashDone, setSplashDone] = React.useState(false);
  React.useEffect(() => {
    const timer = setTimeout(() => setSplashDone(true), SPLASH_MIN_MS);
    return () => clearTimeout(timer);
  }, []);
  // Use PlasmicHomepage to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicHomepage are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.

  // GlobalContextsProvider supplies CmsCredentialsProvider. Without it the
  // CmsQueryRepeater on this page has no credentials and renders its empty
  // state, so the homepage shows no CMS content at all. Plasmic adds this
  // wrapper only to the page files it generates; this one was generated
  // without it, and since the file is ours a later sync will not add it.
  // It belongs here rather than in _app.tsx: the [slug].tsx pages already
  // wrap themselves, and nesting the provider crashes the production build.
  return (
    <GlobalContextsProvider>
      <PlasmicQueryDataProvider>
        <PageParamsProvider__
          route={useRouter()?.pathname}
          params={useRouter()?.query}
          query={useRouter()?.query}
        >
          <EyeLoader hidden={splashDone} />
          <PlasmicHomepage />
        </PageParamsProvider__>
      </PlasmicQueryDataProvider>
    </GlobalContextsProvider>
  );
}

export default Homepage;
