/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7nJ7UcFmq9UzB6eXfC5z4a

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 7nJ7UcFmq9UzB6eXfC5z4a/projectModule

const data = {
  base: `${"plasmic_tokens_7nJ7UcFmq9UzB6eXfC5z4a"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
