/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: szjgMQpPpxhmkjnaBvZQJG

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: szjgMQpPpxhmkjnaBvZQJG/projectModule

const data = {
  base: `${"plasmic_tokens_szjgMQpPpxhmkjnaBvZQJG"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
