/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: hPz6Q3nQJn9Q8DTBgANGwo

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: hPz6Q3nQJn9Q8DTBgANGwo/projectModule

const data = {
  base: `${"plasmic_tokens_hPz6Q3nQJn9Q8DTBgANGwo"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
